spring:
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:

logging:
  level:
    '': INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
