spring:
  application:
    name: rx-smoker
  datasource:
    url: jdbc:h2:mem:smoker;DB_CLOSE_ON_EXIT=FALSE
    username: smoker
    password: smoker

leader:
  election:
    lock-key: services/rx-smoker/leader
    instance-id: ${INSTANCE_ID}
    token: ${CONSUL_TOKEN}
    polling-delay: 10000 # milliseconds
    polling-duration: 50 # seconds
