spring:
  application:
    name: rx-smoker
  datasource:
    url: jdbc:h2:mem:smoker;DB_CLOSE_ON_EXIT=FALSE
    username: smoker
    password: smoker

leader:
  election:
    lock-key: services/${spring.application.name}/leader
    self-id: ${INSTANCE_ID}
    polling-delay: 10000 # milliseconds
    checks:
      - service:rx-smoker # application health check
      - serfHealth # consul node health check
