CREATE TABLE USER (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	first_name varchar(255) not null,
	last_name varchar(255) not null
);

CREATE TABLE STOCK_QUOTATION (
  id UUID GENERATED BY DEFAULT AS IDENTITY,
  stock varchar(225) not null,
  value double not null,
  timestamp timestamp not null,
  open_value double not null,
  high_value double not null,
  low_value double not null,
  volume double not null
);
